on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'labeled' || github.event.label.name == 'test-all-python-versions' }}
    strategy:
      matrix:
        python-version: ${{ contains(github.event.pull_request.labels.*.name, 'test-all-python-versions') && 
                            fromJSON('["3.12", "3.11"]') ||
                            fromJSON('["3.11"]') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: python3 --version
